import { 
  AbbreviatedClassicConditions, 
  SurrenderTypes, 
  DoubleDownOn,
  PayRatio,
  CharlieType
} from "../classic-models/classic-conditions.model";

export const defaultClassicConditions: AbbreviatedClassicConditions = {
  title: "Default Conditions",
  S17: false,
  RSA:  false,
  MHFS: 4,
  DSA: false,
  DRSA: false,
  DFL: true,
  DAS: true,
  MSE: true,
  reshuffleOnDealerChange: false,
  cardsBurnedOnDealerChange: 1,
  payRatio: PayRatio.THREE_to_TWO,
  spotsPerTable: 7,
  decksPerShoe: 6,
  cardsBurned: 1,
  minBet: 5,
  maxBet: 1000,
  shufflePoint: 260,
  handsPerDealer: 500,
  canDoubleOn:  DoubleDownOn.ANY_TWO_CARDS,
  surrender: SurrenderTypes.NOT_ALLOWED,
  countBurnCard: false,
  countBottomCard: false,
  charlieType: CharlieType.NONE,
  charliePayout: PayRatio.TWO_to_ONE,
  bonusFor678: null,
  bonusFor678Suited: null,
  bonusFor777: null,
  bonusFor777Suited: null,
  bonusForSuitedBlackjack: null,
  bonusForSuitedBlackjackOfSpades: null,
  allowTripleDownOn3Cards: null,
  allowTripleDownOnAnyAmountOfCards: null,
  allowSurrenderAferDouble: null,
  allowSurrenderAtAnyTime: null,
  allowDoubleDownOn3CardsWith9Thru11: null,
  allowDoubleDownOnAny3Cards: null,
  allowDoubleDownOnAnyNumberOfCards: null,
  dealerPushesOn22: null,
  holeCardPolicy: null, 
  doubleExposure: null,
  DXTIES: null,
  DXTIEDBJ: null,
  DXSPLIT10: null,
};

export const normalClassicConditions: AbbreviatedClassicConditions = {
  title: "Normal Conditions",
  S17: true,
  RSA:  true,
  MHFS: 9,
  DSA: true,
  DRSA: true,
  DFL: true,
  DAS: true,
  MSE: true,
  reshuffleOnDealerChange: true,
  cardsBurnedOnDealerChange: 1,
  payRatio: PayRatio.THREE_to_TWO,
  spotsPerTable: 8,
  decksPerShoe: 8,
  cardsBurned: 8,
  minBet: 8,
  maxBet: 80000,
  shufflePoint: 260,
  handsPerDealer: 70,
  canDoubleOn:  DoubleDownOn.ANY_TWO_CARDS,
  surrender: SurrenderTypes.NOT_ALLOWED,
  countBurnCard: true,
  countBottomCard: true,
  charlieType: CharlieType.NONE,
  charliePayout: PayRatio.TWO_to_ONE,
  bonusFor678: null,
  bonusFor678Suited: null,
  bonusFor777: null,
  bonusFor777Suited: null,
  bonusForSuitedBlackjack: null,
  bonusForSuitedBlackjackOfSpades: null,
  allowTripleDownOn3Cards: null,
  allowTripleDownOnAnyAmountOfCards: null,
  allowSurrenderAferDouble: null,
  allowSurrenderAtAnyTime: null,
  allowDoubleDownOn3CardsWith9Thru11: null,
  allowDoubleDownOnAny3Cards: null,
  allowDoubleDownOnAnyNumberOfCards: null,
  dealerPushesOn22: null,
  holeCardPolicy: null,
  doubleExposure: null,
  DXTIES: null,
  DXTIEDBJ: null,
  DXSPLIT10: null, 
}

export const deviationClassicConditions: AbbreviatedClassicConditions = {
  title: "Deviation Conditions",
  S17: false,
  RSA:  false,
  MHFS: 4,
  DSA: false,
  DRSA: false,
  DFL: true,
  DAS: true,
  MSE: true,
  reshuffleOnDealerChange: false,
  cardsBurnedOnDealerChange: 1,
  payRatio: PayRatio.THREE_to_TWO,
  spotsPerTable: 7,
  decksPerShoe: 6,
  cardsBurned: 1,
  minBet: 5,
  maxBet: 1000,
  shufflePoint: 83,
  handsPerDealer: 500,
  canDoubleOn:  DoubleDownOn.ANY_TWO_CARDS,
  surrender: SurrenderTypes.NOT_ALLOWED,
  countBurnCard: false,
  countBottomCard: false,
  charlieType: CharlieType.NONE,
  charliePayout: PayRatio.TWO_to_ONE,
  bonusFor678: null,
  bonusFor678Suited: null,
  bonusFor777: null,
  bonusFor777Suited: null,
  bonusForSuitedBlackjack: null,
  bonusForSuitedBlackjackOfSpades: null,
  allowTripleDownOn3Cards: null,
  allowTripleDownOnAnyAmountOfCards: null,
  allowSurrenderAferDouble: null,
  allowSurrenderAtAnyTime: null,
  allowDoubleDownOn3CardsWith9Thru11: null,
  allowDoubleDownOnAny3Cards: null,
  allowDoubleDownOnAnyNumberOfCards: null,
  dealerPushesOn22: null,
  holeCardPolicy: null,
  doubleExposure: null,
  DXTIES: null,
  DXTIEDBJ: null,
  DXSPLIT10: null,
}

export const storedConditionTitles: string[] = [
  "Default Conditions",
  "Normal Conditions",
  "Deviation Conditions", // TODO - This might not need to be included here as this is for finding deviations
];

export const allDefaultClassicConditions: { [k: string]: AbbreviatedClassicConditions } = {
  "Default Conditions": defaultClassicConditions,
  "Normal Conditions": normalClassicConditions,
  "Deviation Conditions": deviationClassicConditions,
};