import { 
  AbbreviatedClassicConditions, 
  SurrenderTypes, 
  DoubleDownOn,
  PayRatio,
  CharlieType,
  HoleCardType
} from "../classic-models/classic-strategies.models";

export const classicDefaultConditions: AbbreviatedClassicConditions = {
  title: "Default Conditions",
  S17: false,
  RSA:  false,
  MHFS: 4,
  DSA: false,
  DRSA: false,
  DFL: true,
  DAS: true,
  MSE: true,
  reshuffleOnDealerChange: false,
  cardsBurnedOnDealerChange: 1,
  blackjackPayRatio: PayRatio.THREE_to_TWO,
  spotsPerTable: 7,
  decksPerShoe: 6,
  cardsBurned: 1,
  minBet: 5,
  maxBet: 1000,
  shufflePoint: 260,
  handsPerDealer: 500,
  canDoubleOn:  DoubleDownOn.ANY_TWO_CARDS,
  surrender: SurrenderTypes.NOT_ALLOWED,
  countBurnCard: false,
  countBottomCard: false,
  charlieAfterSplit: false,
  charlieType: CharlieType.NONE,
  charliePayout: PayRatio.N_A,
  bonusFor678: null,
  bonusFor678Payout: PayRatio.N_A,
  isBonusFor678Guaranteed: false, 
  bonusFor678Suited: null,
  bonusFor678SuitedPayout: PayRatio.N_A,
  isBonusFor678SuitedGuaranteed: false,
  bonusFor678Spaded: null,
  bonusFor678SpadedPayout: PayRatio.N_A,
  isBonusFor678SpadedGuaranteed: false,
  bonusFor777: null,
  bonusFor777Payout: PayRatio.N_A,
  isBonusFor777Guaranteed: false, 
  bonusFor777Suited: null,
  bonusFor777SuitedPayout: PayRatio.N_A,
  isBonusFor777SuitedGuaranteed: false, 
  bonusFor777Spaded: null,
  bonusFor777SpadedPayout: PayRatio.N_A,
  isBonusFor777SpadedGuaranteed: false, 
  bonusForSuitedBlackjack: null,
  bonusForSuitedBlackjackPayout: PayRatio.N_A,
  isBonusForSuitedBlackjackGuaranteed: false,
  bonusForSuitedBlackjackOfSpades: null,
  bonusForSuitedBlackjackOfSpadesPayout: PayRatio.N_A,
  isBonusForSuitedBlackjackOfSpadesGuaranteed: false,
  allowTripleDownOn3Cards: false,
  allowTripleDownOnAnyAmountOfCards: false,
  allowSurrenderAferDouble: false,
  allowSurrenderAtAnyTime: false,
  allowDoubleDownOn3CardsWith9Thru11: false,
  allowDoubleDownOnAny3Cards: false,
  allowDoubleDownOnAnyNumberOfCards: false,
  dealerPushesOn22: false,
  holeCardPolicy: HoleCardType.STANDARD, 
  doubleExposure: null,
  DXTIES: null,
  DXTIEDBJ: null,
  DXSPLIT10: null,
};

export const normalClassicConditions: AbbreviatedClassicConditions = {
  title: "Normal Conditions",
  S17: true,
  RSA:  true,
  MHFS: 4,
  DSA: true,
  DRSA: true,
  DFL: true,
  DAS: true,
  MSE: true,
  reshuffleOnDealerChange: true,
  cardsBurnedOnDealerChange: 1,
  blackjackPayRatio: PayRatio.THREE_to_TWO,
  spotsPerTable: 3,
  decksPerShoe: 4,
  cardsBurned: 1,
  minBet: 5,
  maxBet: 100,
  shufflePoint: 160,
  handsPerDealer: 100,
  canDoubleOn:  DoubleDownOn.ANY_TWO_CARDS,
  surrender: SurrenderTypes.NOT_ALLOWED,
  countBurnCard: true,
  countBottomCard: true,
  charlieAfterSplit: false,
  charlieType: CharlieType.NONE,
  charliePayout: PayRatio.N_A,
  bonusFor678: null,
  bonusFor678Payout: PayRatio.N_A,
  isBonusFor678Guaranteed: false, 
  bonusFor678Suited: null,
  bonusFor678SuitedPayout: PayRatio.N_A,
  isBonusFor678SuitedGuaranteed: false,
  bonusFor678Spaded: null,
  bonusFor678SpadedPayout: PayRatio.N_A,
  isBonusFor678SpadedGuaranteed: false,
  bonusFor777: null,
  bonusFor777Payout: PayRatio.N_A,
  isBonusFor777Guaranteed: false, 
  bonusFor777Suited: null,
  bonusFor777SuitedPayout: PayRatio.N_A,
  isBonusFor777SuitedGuaranteed: false,
  bonusFor777Spaded: null,
  bonusFor777SpadedPayout: PayRatio.N_A,
  isBonusFor777SpadedGuaranteed: false, 
  bonusForSuitedBlackjack: null,
  bonusForSuitedBlackjackPayout: PayRatio.N_A,
  isBonusForSuitedBlackjackGuaranteed: false,
  bonusForSuitedBlackjackOfSpades: null,
  bonusForSuitedBlackjackOfSpadesPayout: PayRatio.N_A,
  isBonusForSuitedBlackjackOfSpadesGuaranteed: false,
  allowTripleDownOn3Cards: false,
  allowTripleDownOnAnyAmountOfCards: false,
  allowSurrenderAferDouble: false,
  allowSurrenderAtAnyTime: false,
  allowDoubleDownOn3CardsWith9Thru11: false,
  allowDoubleDownOnAny3Cards: false,
  allowDoubleDownOnAnyNumberOfCards: false,
  dealerPushesOn22: false,
  holeCardPolicy: HoleCardType.STANDARD, 
  doubleExposure: null,
  DXTIES: null,
  DXTIEDBJ: null,
  DXSPLIT10: null, 
}

export const deviationClassicConditions: AbbreviatedClassicConditions = {
  title: "Deviation Conditions",
  S17: false,
  RSA:  false,
  MHFS: 4,
  DSA: false,
  DRSA: false,
  DFL: true,
  DAS: true,
  MSE: true,
  reshuffleOnDealerChange: false,
  cardsBurnedOnDealerChange: 1,
  blackjackPayRatio: PayRatio.THREE_to_TWO,
  spotsPerTable: 7,
  decksPerShoe: 6,
  cardsBurned: 1,
  minBet: 5,
  maxBet: 1000,
  shufflePoint: 83,
  handsPerDealer: 500,
  canDoubleOn:  DoubleDownOn.ANY_TWO_CARDS,
  surrender: SurrenderTypes.NOT_ALLOWED,
  countBurnCard: false,
  countBottomCard: false,
  charlieAfterSplit: false,
  charlieType: CharlieType.NONE,
  charliePayout: PayRatio.N_A,
  bonusFor678: null,
  bonusFor678Payout: PayRatio.N_A,
  isBonusFor678Guaranteed: false, 
  bonusFor678Suited: null,
  bonusFor678SuitedPayout: PayRatio.N_A,
  isBonusFor678SuitedGuaranteed: false,
  bonusFor678Spaded: null,
  bonusFor678SpadedPayout: PayRatio.N_A,
  isBonusFor678SpadedGuaranteed: false,
  bonusFor777: null,
  bonusFor777Payout: PayRatio.N_A,
  isBonusFor777Guaranteed: false, 
  bonusFor777Suited: null,
  bonusFor777SuitedPayout: PayRatio.N_A,
  isBonusFor777SuitedGuaranteed: false, 
  bonusFor777Spaded: null,
  bonusFor777SpadedPayout: PayRatio.N_A,
  isBonusFor777SpadedGuaranteed: false, 
  bonusForSuitedBlackjack: null,
  bonusForSuitedBlackjackPayout: PayRatio.N_A,
  isBonusForSuitedBlackjackGuaranteed: false,
  bonusForSuitedBlackjackOfSpades: null,
  bonusForSuitedBlackjackOfSpadesPayout: PayRatio.N_A,
  isBonusForSuitedBlackjackOfSpadesGuaranteed: false,
  allowTripleDownOn3Cards: false,
  allowTripleDownOnAnyAmountOfCards: false,
  allowSurrenderAferDouble: false,
  allowSurrenderAtAnyTime: false,
  allowDoubleDownOn3CardsWith9Thru11: false,
  allowDoubleDownOnAny3Cards: false,
  allowDoubleDownOnAnyNumberOfCards: false,
  dealerPushesOn22: false,
  holeCardPolicy: HoleCardType.STANDARD, 
  doubleExposure: null,
  DXTIES: null,
  DXTIEDBJ: null,
  DXSPLIT10: null,
}

export const classicConditionTitles: string[] = [
  "Default Conditions",
  "Normal Conditions",
  "Deviation Conditions",
];

export const classicConditions: { [k: string]: AbbreviatedClassicConditions } = {
  "Default Conditions": classicDefaultConditions,
  "Normal Conditions": normalClassicConditions,
  "Deviation Conditions": deviationClassicConditions,
};

export const defaultClassicConditions: AbbreviatedClassicConditions = classicDefaultConditions;