export const classicFeatureToggles = {
  isStandard: true,
  doubleForLess: false,
  doubleSplitAces: false,
  drawOnSplitAces: false,
  enhancedSurrender: false,
  has5CardsCharlie: false,
  has6CardsCharlie: false,
  bonusFor678: false,
  bonusFor678Suited: false,
  bonusFor777: false,
  bonusFor777Suited: false,
  bonusForSuitedBlackjack: false,
  bonusForSuitedBlackjackOfSpades: false,
  allowTripleDownOn3Cards: false,
  allowTripleDownOnAnyAmountOfCards: false,
  allowSurrenderAferDouble: false,
  allowSurrenderAtAnyTime: false,
  allowDoubleDownOn3CardsWith9Thru11: false,
  allowDoubleDownOnAny3Cards: false,
  allowDoubleDownOnAnyNumberOfCards: false,
  dealerPushesOn22: false,
  noHoleCard: false,
}

export enum ClassicFeatureToggles {
  IS_STANDARD = 'isStandard',
  DOUBLE_FOR_LESS = 'doubleForLess',
  DOUBLE_SPLIT_ACES = 'doubleSplitAces',
  DRAW_ON_SPLIT_ACES = 'drawOnSplitAces',
  ENHANCED_SURRENDER = 'enhancedSurrender',
  SEEN_CARD_ADVANTAGE = 'seenCardAdvantage',
  HAS_CHARLIE = 'has5CardsCharlie',
  BONUS_FOR_678 = 'bonusFor678',
  BONUS_FOR_678_SUITED = 'bonusFor678Suited',
  BONUS_FOR_777 = 'bonusFor777',
  BONUS_FOR_777_SUITED = 'bonusFor777Suited',
  BONUS_FOR_SUITED_BLACKJACK = 'bonusForSuitedBlackjack',
  BONUS_FOR_SUITED_BLACKJACK_OF_SPADES = 'bonusForSuitedBlackjackOfSpades',
  ALLOW_TRIPLE_DOWN_ON_3_CARDS = 'allowTripleDownOn3Cards',
  ALLOW_TRIPLE_DOWN_ON_ANY_AMOUNT_OF_CARDS = 'allowTripleDownOnAnyAmountOfCards',
  ALLOW_SURRENDER_AFTER_DOUBLE = 'allowSurrenderAferDouble',
  ALLOW_SURRENDER_AT_ANY_TIME = 'allowSurrenderAtAnyTime',
  ALLOW_DOUBLE_DOWN_ON_3_CARDS_WITH_9_THRU_11 = 'allowDoubleDownOn3CardsWith9Thru11',
  ALLOW_DOUBLE_DOWN_ON_ANY_3_CARDS = 'allowDoubleDownOnAny3Cards',
  ALLOW_DOUBLE_DOWN_ON_ANY_NUMBER_OF_CARDS = 'allowDoubleDownOnAnyNumberOfCards',
  DEALER_PUSHES_ON_22 = 'dealerPushesOn22',
  NHC = 'noHoleCard',
  DX = 'doubleExposure'
}

export enum ClassicFeatureGroups {
  STANDARD = 'standard',
  EV_HACKS = 'evHacks',
  BONUSES = 'bonuses',
  WEIRD_RULES = 'weirdRules',
  CAMO_PLAYS = 'camoPlays',
}