import { FeatureDetails } from "../../models";

export const featureSteps: FeatureDetails[] = [
    {
    imgSrc: 'how-to-simulation-images/runasimulation.png',
    imgAltText: 'Run a Simulation',
    headerText: 'What does it take to run a simulation?',
    taglineText:  'There\'s just 2 things you need',
    textContent: [
      'To run a simulation, you just need 2 things',
      'Select a table, prebuilt or custom',
      'Select a number of rounds',
      'Results are more accurate the more rounds you run.',
      'We are tracking AV. With enough rounds AV and EV converge',
    ],
    videoUrl: 'runASimulationUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/makeatable.png',
    imgAltText: 'Make your own table',
    headerText: 'How do I make my own table?',
    taglineText:  'There\'s just a few steps',
    textContent: [
      'To make a table, you just need 2 things',
      'Select the players you want, prebuilt or custom',
      'Position them in the spots you want, leave room to wong.',
      'Select the conditions you want',
      'Save it',
      'Run a simulation with your custom table',
    ],
    videoUrl: 'buildATableUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/setconditions.png',
    imgAltText: 'set custom conditions',
    headerText: 'How do I set table conditions?',
    taglineText:  'Playing or avoiding a table comes down to the table conditions.',
    textContent: [
      'ANy the condition you have ever heard of is included',
      'Many conditions you haven\'t heard of are includes',
      'Some variations, like classic blackjack, even have promotions, like blackjack pays 2:1',
      'Select the conditions you want then save them',
      'Add your conditions to new table or update an old one',
      'Add the table to a simulation',
      'Compare results'
    ],
    videoUrl: 'setConditionsUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/createaplayer.png',
    imgAltText: 'build your own player',
    headerText: 'How do I build my own player?',
    taglineText:  'Mix and match behaviors to build a unique player',
    textContent: [
      'Besides things like the players name, starting bankroll, betting unit there are several different behaviors that make a player unique',
      'Play with different bet spreads. Make players with tight or aggressive betspreads.',
      'In real life, players resize their betting unit up or down',
      'Do you want to try a fifferent counting system?',
      'If you are going to tip, you might as well build it into the system',
      'Wong in or out of additional hands as the count moves up and down.',
      'Experiment with when to take insurance. This will make more sense after you have analysed insurance EV at different counts with dirrerent counting systems.',
      'If you are going to use a different counting system, you probably want a deviation chart to go with it.',
      "To test your player, add it to a new table or update an existing table.",
      "Run a simulation with that players, or players.",
      "You can now compare results from different counting systems, or see the extra EV generated from using a deviations chart over a basic strategy chart.",
    ],
    videoUrl: 'buildAPlayerUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/createbetspread.png',
    imgAltText: 'create a betspread',
    headerText: 'What does creating a bet spread look like?',
    taglineText:  'Most of the reason you count is to know when to spread your bet.',
    textContent: [
      'For each count decide how many betting units you would like to bet',
      'The highest unit you bet will be the bet size for any count higher',
      'The lowest unit you bet will be the unit size you bet for any counts lower',
      'If you want to adjust your bet to a bet size of zero, you can, but if there is no other player at your table, cards will be dealt to you. This may skew the results.',
      'Spread your bets as far as you want for as many different consecutive counts you want'
    ],
    videoUrl: 'createABetSpreadUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/createunitresizingstrategy.png',
    imgAltText: 'create a unit resizing strategy',
    headerText: 'What does "Unit Resizing" mean?',
    taglineText:  'When your bankroll changes, so should your base betsize',
    textContent: [
      'Your betting unit is your smallest bet size (usually), of whatever you usually bet at TC0',
      'As your bank roll grows, you probably want to up your minimum bet as well.',
      'On the other hand, if you loose enough of your bankroll, you may need to drop your minimum bet',
      'Implement a plan for both cases',
      'as many times as you want',
      'Often you will want to reduce your risk as your bankroll grows by growing your bets slower than you grow your bankroll',
      'Create a new player, or update an existing player with you new unit resizing strategy',
    ],
    videoUrl: 'makeAUnitResizingStrategyUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/createwongingstrategy.png',
    imgAltText: 'build your own player',
    headerText: 'How do I build my own player?',
    taglineText:  'Mix and match behaviors to build a unique player',
    textContent: [
      'Once you build a player or any other configuration once, you don\'t have to ever build it again.',
      'Start with the player\'s name and bankroll.',
      'Add a bet spread and a plan for resizing the betting unit.',
      'Use the counting system of your choice and a deviation chart to go with it.',
      'Make a plan to wong in and out with the count.',
      'Experiment with when to take insurance.',
      'Might as well make tipping a part of the simulation.',
      'For any configurations, chose a built-in one or create and save your own.',
    ],
    videoUrl: 'buildAPlayerUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/createtippingapproach.png',
    imgAltText: 'build your own player',
    headerText: 'How do I build my own player?',
    taglineText:  'Mix and match behaviors to build a unique player',
    textContent: [
      'Once you build a player or any other configuration once, you don\'t have to ever build it again.',
      'Start with the player\'s name and bankroll.',
      'Add a bet spread and a plan for resizing the betting unit.',
      'Use the counting system of your choice and a deviation chart to go with it.',
      'Make a plan to wong in and out with the count.',
      'Experiment with when to take insurance.',
      'Might as well make tipping a part of the simulation.',
      'For any configurations, chose a built-in one or create and save your own.',
    ],
    videoUrl: 'buildAPlayerUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/makeacountingsystem.png',
    imgAltText: 'build your own player',
    headerText: 'How do I build my own player?',
    taglineText:  'Mix and match behaviors to build a unique player',
    textContent: [
      'Once you build a player or any other configuration once, you don\'t have to ever build it again.',
      'Start with the player\'s name and bankroll.',
      'Add a bet spread and a plan for resizing the betting unit.',
      'Use the counting system of your choice and a deviation chart to go with it.',
      'Make a plan to wong in and out with the count.',
      'Experiment with when to take insurance.',
      'Might as well make tipping a part of the simulation.',
      'For any configurations, chose a built-in one or create and save your own.',
    ],
    videoUrl: 'buildAPlayerUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/makeadeviationchart.png',
    imgAltText: 'build your own player',
    headerText: 'How do I build my own player?',
    taglineText:  'Mix and match behaviors to build a unique player',
    textContent: [
      'Once you build a player or any other configuration once, you don\'t have to ever build it again.',
      'Start with the player\'s name and bankroll.',
      'Add a bet spread and a plan for resizing the betting unit.',
      'Use the counting system of your choice and a deviation chart to go with it.',
      'Make a plan to wong in and out with the count.',
      'Experiment with when to take insurance.',
      'Might as well make tipping a part of the simulation.',
      'For any configurations, chose a built-in one or create and save your own.',
    ],
    videoUrl: 'buildAPlayerUrl',
    buttontext: 'Watch and Learn',
  },
  {
    imgSrc: 'how-to-simulation-images/createinsuranceplan.png',
    imgAltText: 'build your own player',
    headerText: 'How do I build my own player?',
    taglineText:  'Mix and match behaviors to build a unique player',
    textContent: [
      'Once you build a player or any other configuration once, you don\'t have to ever build it again.',
      'Start with the player\'s name and bankroll.',
      'Add a bet spread and a plan for resizing the betting unit.',
      'Use the counting system of your choice and a deviation chart to go with it.',
      'Make a plan to wong in and out with the count.',
      'Experiment with when to take insurance.',
      'Might as well make tipping a part of the simulation.',
      'For any configurations, chose a built-in one or create and save your own.',
    ],
    videoUrl: 'buildAPlayerUrl',
    buttontext: 'Watch and Learn',
  },
];